title: >
  Jim Merritt's Banner Ads
description: >
  A collection of banner ad tempaltes I put together to save development time. Each banner
  ad has an HTML file, CSS(Sass) file, and JS file if not a mobile banner.
production: false

baseurl: ""
url: ""

exclude: [.gitignore, .sass-cahe, gulpfile.js, node_modules, package.json, README.txt]
markdown: kramdown
